//! Resource-preserving helpers shared by the `WASIp3` middleware components.

#![deny(missing_docs)]

use std::sync::{
    OnceLock,
    atomic::{AtomicU64, Ordering},
};

use http::{HeaderMap, HeaderName, HeaderValue};
use wasip3::http::types::{ErrorCode, Headers, Method, Request, Response, Scheme};
use wasip3::wit_future;

/// Generates the pinned `WASIp3` middleware world while reusing `wasip3`'s
/// resource types for every shared interface.
///
/// Invoke this macro inside a private `bindings` module in each component.
/// The path is resolved relative to the invoking crate, allowing published
/// consumers to provide their own pinned WIT package directory. When running
/// Rust 1.95 Clippy with pedantic lints, annotate that private module with
/// `#[allow(clippy::same_length_and_capacity)]`; the diagnosed allocation is
/// generated by `wit-bindgen` 0.59 rather than by the component.
#[macro_export]
macro_rules! generate_middleware_bindings {
    ($path:literal) => {
        ::wit_bindgen::generate!({
            path: $path,
            world: "wasi:http/middleware",
            with: {
                "wasi:http/types@0.3.0": ::wasip3::http::types,
                "wasi:http/client@0.3.0": ::wasip3::http::client,
                "wasi:random/random@0.3.0": ::wasip3::random::random,
                "wasi:random/insecure@0.3.0": ::wasip3::random::insecure,
                "wasi:random/insecure-seed@0.3.0": ::wasip3::random::insecure_seed,
                "wasi:cli/stdout@0.3.0": ::wasip3::cli::stdout,
                "wasi:cli/stderr@0.3.0": ::wasip3::cli::stderr,
                "wasi:cli/stdin@0.3.0": ::wasip3::cli::stdin,
                "wasi:cli/types@0.3.0": ::wasip3::cli::types,
                "wasi:clocks/monotonic-clock@0.3.0": ::wasip3::clocks::monotonic_clock,
                "wasi:clocks/system-clock@0.3.0": ::wasip3::clocks::system_clock,
                "wasi:clocks/types@0.3.0": ::wasip3::clocks::types,
            },
        });
    };
}

/// One HTTP field as exposed by `wasi:http/types`.
pub type Header = (String, Vec<u8>);

const REQUEST_ID_PREFIX_BYTES: usize = 16;
const REQUEST_ID_CAPACITY: usize = (REQUEST_ID_PREFIX_BYTES + size_of::<u64>()) * 2;

static REQUEST_ID_PREFIX: OnceLock<[u8; REQUEST_ID_PREFIX_BYTES]> = OnceLock::new();
static REQUEST_ID_SEQUENCE: AtomicU64 = AtomicU64::new(0);

/// A field could not be converted between WASI HTTP and `http` crate types.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct HeaderConversionError;

impl std::fmt::Display for HeaderConversionError {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str("invalid HTTP field")
    }
}

impl std::error::Error for HeaderConversionError {}

/// Returns an owned copy of a request's header fields.
pub fn request_headers(request: &Request) -> Vec<Header> {
    request.get_headers().copy_all()
}

/// Returns an owned copy of a response's header fields.
pub fn response_headers(response: &Response) -> Vec<Header> {
    response.get_headers().copy_all()
}

/// Returns every value for `name`, compared case-insensitively.
pub fn header_values<'a>(headers: &'a [Header], name: &str) -> Vec<&'a [u8]> {
    headers
        .iter()
        .filter(|(candidate, _)| candidate.eq_ignore_ascii_case(name))
        .map(|(_, value)| value.as_slice())
        .collect()
}

/// Removes every field named `name`, compared case-insensitively.
pub fn remove_header(headers: &mut Vec<Header>, name: &str) {
    headers.retain(|(candidate, _)| !candidate.eq_ignore_ascii_case(name));
}

/// Removes every field whose name starts with `prefix`, compared
/// case-insensitively.
pub fn remove_headers_with_prefix(headers: &mut Vec<Header>, prefix: &str) {
    headers.retain(|(candidate, _)| {
        candidate
            .get(..prefix.len())
            .is_none_or(|start| !start.eq_ignore_ascii_case(prefix))
    });
}

/// Replaces every field named `name` with one canonical field.
pub fn set_header(headers: &mut Vec<Header>, name: &str, value: impl Into<Vec<u8>>) {
    remove_header(headers, name);
    headers.push((name.to_ascii_lowercase(), value.into()));
}

/// Generates a non-secret, safe ASCII request ID.
///
/// One random 128-bit prefix is allocated per component instance. A relaxed
/// monotonic 64-bit sequence then guarantees distinct IDs within that
/// instance until the sequence wraps. The resulting 48-character lowercase
/// hexadecimal value is suitable for propagation and logging, but must not be
/// treated as an authentication token.
pub fn generated_request_id() -> String {
    let prefix = REQUEST_ID_PREFIX.get_or_init(|| {
        let random = wasip3::random::random::get_random_bytes(REQUEST_ID_PREFIX_BYTES as u64);
        let mut prefix = [0_u8; REQUEST_ID_PREFIX_BYTES];
        for (target, source) in prefix.iter_mut().zip(random) {
            *target = source;
        }
        prefix
    });
    encode_request_id(prefix, REQUEST_ID_SEQUENCE.fetch_add(1, Ordering::Relaxed))
}

fn encode_request_id(prefix: &[u8; REQUEST_ID_PREFIX_BYTES], sequence: u64) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut output = String::with_capacity(REQUEST_ID_CAPACITY);
    for byte in prefix.iter().copied().chain(sequence.to_be_bytes()) {
        output.push(char::from(HEX[usize::from(byte >> 4)]));
        output.push(char::from(HEX[usize::from(byte & 0x0f)]));
    }
    output
}

/// Converts WASI HTTP fields to an `http` header map without collapsing
/// duplicate values.
///
/// # Errors
///
/// Returns [`HeaderConversionError`] when a field name or value is invalid.
pub fn to_header_map(headers: &[Header]) -> Result<HeaderMap, HeaderConversionError> {
    let mut output = HeaderMap::new();
    for (name, value) in headers {
        let name = HeaderName::from_bytes(name.as_bytes()).map_err(|_| HeaderConversionError)?;
        let mut value = HeaderValue::from_bytes(value).map_err(|_| HeaderConversionError)?;
        if is_sensitive_header(&name) {
            value.set_sensitive(true);
        }
        output.append(name, value);
    }
    Ok(output)
}

fn is_sensitive_header(name: &HeaderName) -> bool {
    matches!(
        name.as_str(),
        "authorization" | "proxy-authorization" | "cookie" | "set-cookie"
    ) || name.as_str().starts_with("x-wasi-auth-")
}

/// Converts an `http` header map to WASI HTTP fields while retaining all
/// duplicate values.
pub fn from_header_map(headers: &HeaderMap) -> Vec<Header> {
    let mut output = Vec::with_capacity(headers.len());
    for name in headers.keys() {
        for value in headers.get_all(name) {
            output.push((name.as_str().to_owned(), value.as_bytes().to_vec()));
        }
    }
    output
}

/// Replaces fields in `target` with every field present in `source`.
pub fn merge_header_map(target: &mut Vec<Header>, source: &HeaderMap) {
    for name in source.keys() {
        remove_header(target, name.as_str());
        for value in source.get_all(name) {
            target.push((name.as_str().to_owned(), value.as_bytes().to_vec()));
        }
    }
}

/// Rebuilds `request` with `headers` while forwarding its body stream, trailers,
/// request options, method, scheme, path/query, and authority unchanged.
///
/// The body stream is transferred directly into the new request and is never
/// read, buffered, or copied.
///
/// # Errors
///
/// Returns a WASI HTTP error when the requested header changes or request
/// metadata cannot be applied to the forwarded request.
pub fn replace_request_headers(request: Request, headers: &[Header]) -> Result<Request, ErrorCode> {
    let original_fields = request_headers(&request);
    replace_request_headers_from_original(request, &original_fields, headers)
}

/// Rebuilds `request` with `headers`, reusing an already-copied view of the
/// original fields while forwarding its body stream, trailers, request
/// options, method, scheme, path/query, and authority unchanged.
///
/// This is equivalent to [`replace_request_headers`] but avoids a second
/// `copy-all` host call when a middleware has already inspected the original
/// fields.
///
/// # Errors
///
/// Returns a WASI HTTP error when the requested header changes or request
/// metadata cannot be applied to the forwarded request.
pub fn replace_request_headers_from_original(
    request: Request,
    original_fields: &[Header],
    headers: &[Header],
) -> Result<Request, ErrorCode> {
    let original_headers = request.get_headers();
    let forwarded_headers = original_headers.clone();
    drop(original_headers);
    apply_header_diff(&forwarded_headers, original_fields, headers)
        .map_err(|()| request_header_error())?;

    let method = request.get_method();
    let scheme = request.get_scheme();
    let path_with_query = request.get_path_with_query();
    let authority = request.get_authority();
    let options = request.get_options();
    let (body_result_writer, body_result) = wit_future::new(|| Err(ErrorCode::InternalError(None)));
    let (body, trailers) = Request::consume_body(request, body_result);

    let (forwarded, transmission_result) =
        Request::new(forwarded_headers, Some(body), trailers, options);
    wit_bindgen::spawn_local(async move {
        let result = transmission_result.await;
        let _write_result = body_result_writer.write(result).await;
    });
    restore_request_metadata(
        &forwarded,
        &method,
        scheme.as_ref(),
        path_with_query.as_deref(),
        authority.as_deref(),
    )?;
    Ok(forwarded)
}

/// Rebuilds `request` after applying only the named header deletions and
/// replacements to a clone of its host-owned header resource.
///
/// Unlike [`replace_request_headers`], this avoids copying and diffing the
/// complete header list. Each replacement name is canonicalized to the values
/// supplied for that name; fields not named by either slice remain untouched.
/// The body stream, trailers, request options, method, scheme, path/query, and
/// authority are forwarded unchanged.
///
/// # Errors
///
/// Returns a WASI HTTP error when a requested edit or request metadata cannot
/// be applied to the forwarded request.
pub fn edit_request_headers(
    request: Request,
    delete_names: &[&str],
    replacements: &[(&str, &[u8])],
) -> Result<Request, ErrorCode> {
    let original_headers = request.get_headers();
    let forwarded_headers = original_headers.clone();
    drop(original_headers);
    apply_header_edits(&forwarded_headers, delete_names, replacements)
        .map_err(|()| request_header_error())?;

    let method = request.get_method();
    let scheme = request.get_scheme();
    let path_with_query = request.get_path_with_query();
    let authority = request.get_authority();
    let options = request.get_options();
    let (body_result_writer, body_result) = wit_future::new(|| Err(ErrorCode::InternalError(None)));
    let (body, trailers) = Request::consume_body(request, body_result);

    let (forwarded, transmission_result) =
        Request::new(forwarded_headers, Some(body), trailers, options);
    wit_bindgen::spawn_local(async move {
        let result = transmission_result.await;
        let _write_result = body_result_writer.write(result).await;
    });
    restore_request_metadata(
        &forwarded,
        &method,
        scheme.as_ref(),
        path_with_query.as_deref(),
        authority.as_deref(),
    )?;
    Ok(forwarded)
}

/// Rebuilds `response` with `headers` while forwarding its status, body stream,
/// and trailers unchanged.
///
/// The body stream is transferred directly into the new response and is never
/// read, buffered, or copied.
///
/// # Errors
///
/// Returns a WASI HTTP error when the requested header changes or original
/// status code cannot be applied to the forwarded response.
pub fn replace_response_headers(
    response: Response,
    headers: &[Header],
) -> Result<Response, ErrorCode> {
    let original_fields = response_headers(&response);
    replace_response_headers_from_original(response, &original_fields, headers)
}

/// Rebuilds `response` with `headers`, reusing an already-copied view of the
/// original fields while forwarding its status, body stream, and trailers
/// unchanged.
///
/// This is equivalent to [`replace_response_headers`] but avoids a second
/// `copy-all` host call when a middleware has already inspected the original
/// fields.
///
/// # Errors
///
/// Returns a WASI HTTP error when the requested header changes or original
/// status code cannot be applied to the forwarded response.
pub fn replace_response_headers_from_original(
    response: Response,
    original_fields: &[Header],
    headers: &[Header],
) -> Result<Response, ErrorCode> {
    let original_headers = response.get_headers();
    let forwarded_headers = original_headers.clone();
    drop(original_headers);
    apply_header_diff(&forwarded_headers, original_fields, headers)
        .map_err(|()| response_header_error())?;

    let status = response.get_status_code();
    let (body_result_writer, body_result) = wit_future::new(|| Err(ErrorCode::InternalError(None)));
    let (body, trailers) = Response::consume_body(response, body_result);
    let (forwarded, transmission_result) = Response::new(forwarded_headers, Some(body), trailers);
    wit_bindgen::spawn_local(async move {
        let result = transmission_result.await;
        let _write_result = body_result_writer.write(result).await;
    });
    forwarded
        .set_status_code(status)
        .map_err(|()| ErrorCode::InternalError(None))?;
    Ok(forwarded)
}

/// Rebuilds `response` after applying only the named header deletions and
/// replacements to a clone of its host-owned header resource.
///
/// Unlike [`replace_response_headers`], this avoids copying and diffing the
/// complete header list. Each replacement name is canonicalized to the values
/// supplied for that name; fields not named by either slice remain untouched.
/// The status, body stream, and trailers are forwarded unchanged.
///
/// # Errors
///
/// Returns a WASI HTTP error when a requested edit or original status code
/// cannot be applied to the forwarded response.
pub fn edit_response_headers(
    response: Response,
    delete_names: &[&str],
    replacements: &[(&str, &[u8])],
) -> Result<Response, ErrorCode> {
    let original_headers = response.get_headers();
    let forwarded_headers = original_headers.clone();
    drop(original_headers);
    apply_header_edits(&forwarded_headers, delete_names, replacements)
        .map_err(|()| response_header_error())?;

    let status = response.get_status_code();
    let (body_result_writer, body_result) = wit_future::new(|| Err(ErrorCode::InternalError(None)));
    let (body, trailers) = Response::consume_body(response, body_result);
    let (forwarded, transmission_result) = Response::new(forwarded_headers, Some(body), trailers);
    wit_bindgen::spawn_local(async move {
        let result = transmission_result.await;
        let _write_result = body_result_writer.write(result).await;
    });
    forwarded
        .set_status_code(status)
        .map_err(|()| ErrorCode::InternalError(None))?;
    Ok(forwarded)
}

/// Constructs a response with no body and no trailers.
///
/// # Errors
///
/// Returns a WASI HTTP error when the supplied headers or status code cannot
/// be used to construct the response.
pub fn empty_response(status: u16, mut headers: Vec<Header>) -> Result<Response, ErrorCode> {
    if !headers
        .iter()
        .any(|(name, _)| name.eq_ignore_ascii_case("content-length"))
    {
        headers.push(("content-length".to_owned(), b"0".to_vec()));
    }
    let headers = Headers::from_list(&headers).map_err(|_| response_header_error())?;
    let (trailers_writer, trailers) = wit_future::new(|| Ok(None));
    drop(trailers_writer);
    let (response, _transmission_result) = Response::new(headers, None, trailers);
    response
        .set_status_code(status)
        .map_err(|()| ErrorCode::InternalError(None))?;
    Ok(response)
}

fn restore_request_metadata(
    request: &Request,
    method: &Method,
    scheme: Option<&Scheme>,
    path_with_query: Option<&str>,
    authority: Option<&str>,
) -> Result<(), ErrorCode> {
    request
        .set_method(method)
        .and_then(|()| request.set_scheme(scheme))
        .and_then(|()| request.set_path_with_query(path_with_query))
        .and_then(|()| request.set_authority(authority))
        .map_err(|()| ErrorCode::InternalError(None))
}

fn apply_header_diff(fields: &Headers, original: &[Header], desired: &[Header]) -> Result<(), ()> {
    for name in unique_header_names(original) {
        if !contains_header_name(desired, name) {
            fields.delete(name).map_err(|_| ())?;
        }
    }
    for name in unique_header_names(desired) {
        if !header_values_equal(original, desired, name) {
            let values = desired
                .iter()
                .filter(|(candidate, _)| candidate.eq_ignore_ascii_case(name))
                .map(|(_, value)| value.clone())
                .collect::<Vec<_>>();
            fields.set(name, &values).map_err(|_| ())?;
        }
    }
    Ok(())
}

fn apply_header_edits(
    fields: &Headers,
    delete_names: &[&str],
    replacements: &[(&str, &[u8])],
) -> Result<(), ()> {
    for name in unique_names(delete_names) {
        fields.delete(name).map_err(|_| ())?;
    }
    for name in unique_replacement_names(replacements) {
        fields.delete(name).map_err(|_| ())?;
    }
    for (name, value) in replacements {
        fields.append(name, value).map_err(|_| ())?;
    }
    Ok(())
}

fn unique_names<'a>(names: &'a [&'a str]) -> Vec<&'a str> {
    let mut unique = Vec::with_capacity(names.len());
    for name in names {
        if !unique
            .iter()
            .any(|existing: &&str| existing.eq_ignore_ascii_case(name))
        {
            unique.push(*name);
        }
    }
    unique
}

fn unique_replacement_names<'a>(replacements: &'a [(&'a str, &'a [u8])]) -> Vec<&'a str> {
    let mut unique = Vec::with_capacity(replacements.len());
    for (name, _) in replacements {
        if !unique
            .iter()
            .any(|existing: &&str| existing.eq_ignore_ascii_case(name))
        {
            unique.push(*name);
        }
    }
    unique
}

fn unique_header_names(headers: &[Header]) -> Vec<&str> {
    let mut names = Vec::with_capacity(headers.len());
    for (name, _) in headers {
        if !names
            .iter()
            .any(|existing: &&str| existing.eq_ignore_ascii_case(name))
        {
            names.push(name.as_str());
        }
    }
    names
}

fn contains_header_name(headers: &[Header], name: &str) -> bool {
    headers
        .iter()
        .any(|(candidate, _)| candidate.eq_ignore_ascii_case(name))
}

fn header_values_equal(original: &[Header], desired: &[Header], name: &str) -> bool {
    let mut original_values = original
        .iter()
        .filter(|(candidate, _)| candidate.eq_ignore_ascii_case(name))
        .map(|(_, value)| value);
    let mut desired_values = desired
        .iter()
        .filter(|(candidate, _)| candidate.eq_ignore_ascii_case(name))
        .map(|(_, value)| value);
    loop {
        match (original_values.next(), desired_values.next()) {
            (Some(original), Some(desired)) if original == desired => {}
            (None, None) => return true,
            _ => return false,
        }
    }
}

fn request_header_error() -> ErrorCode {
    ErrorCode::HttpRequestHeaderSectionSize(None)
}

fn response_header_error() -> ErrorCode {
    ErrorCode::HttpResponseHeaderSectionSize(None)
}

#[cfg(test)]
mod tests {
    use super::{encode_request_id, remove_headers_with_prefix, to_header_map};

    #[test]
    fn generated_request_id_encoding_is_fixed_width_and_monotonic() {
        let prefix = [0xabu8; 16];
        assert_eq!(
            encode_request_id(&prefix, 1),
            "abababababababababababababababab0000000000000001"
        );
        assert_ne!(encode_request_id(&prefix, 1), encode_request_id(&prefix, 2));
    }

    #[test]
    fn reserved_header_prefix_removal_is_case_insensitive() {
        let mut headers = vec![
            ("X-WASI-AUTH-CONTEXT".to_owned(), b"spoofed".to_vec()),
            ("content-type".to_owned(), b"text/plain".to_vec()),
        ];
        remove_headers_with_prefix(&mut headers, "x-wasi-auth-");
        assert_eq!(
            headers,
            vec![("content-type".to_owned(), b"text/plain".to_vec())]
        );
    }

    #[test]
    fn converted_secret_and_identity_headers_are_debug_sensitive() {
        let headers = to_header_map(&[
            (
                "authorization".to_owned(),
                b"Bearer token-debug-sentinel".to_vec(),
            ),
            (
                "cookie".to_owned(),
                b"session=cookie-debug-sentinel".to_vec(),
            ),
            (
                "x-wasi-auth-context".to_owned(),
                b"identity-debug-sentinel".to_vec(),
            ),
        ])
        .expect("valid headers");

        for value in headers.values() {
            assert!(value.is_sensitive());
        }
        let debug = format!("{headers:?}");
        assert!(!debug.contains("debug-sentinel"));
    }
}
